apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-queue
  namespace: awx
  labels:
    app: awx
    role: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awx
      role: queue
  template:
    metadata:
      labels:
        app: awx
        role: queue
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8
        env:
        - name: RABBITMQ_DEFAULT_VHOST
          value: awx
        ports:
        - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: awx-queue-svc
  namespace: awx
spec:
  ports:
  - name: queue
    port: 5672
    targetPort: 5672
  selector:
    app: awx
    role: queue